# Generated by Django 3.2.25 on 2025-05-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
