# Generated by Django 5.2.3 on 2025-06-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_alter_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/pacientes/'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
